name: peach

on:
  push:
    branches: [main]
    paths:
      - 'apps/pfe/**'
      - 'apps/pfe-e2e/**'
      - 'libs/**'

defaults:
  run:
    working-directory: projects/pfe-platform

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: npm install
        run: npm install
        run: npm prod-pfe:ci
